version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis_container
    environment:
      - REDIS_PASSWORD="12345"
      - REDIS_USER="12345"
      - REDIS_USER_PASSWORD="12345"
    ports:
      - "6379:6379"
    expose:
          - "6379"
    volumes:
      - ./redisdata:/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  shortener:
    container_name: shortener_container
    build: /
    command: go run main.go
    ports:
      - 1234:1234